# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='api.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\tapi.proto\"\x1c\n\x0eGetItemRequest\x12\n\n\x02id\x18\x01 \x01(\t\".\n\x0fListItemRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"[\n\x10ListItemResponse\x12\x14\n\x05items\x18\x01 \x03(\x0b\x32\x05.Item\x12\r\n\x05total\x18\x02 \x01(\x05\x12\x10\n\x08prevPage\x18\x03 \x01(\x05\x12\x10\n\x08nextPage\x18\x04 \x01(\x05\"&\n\x0f\x41\x64\x64ItemResponse\x12\x13\n\x04item\x18\x01 \x01(\x0b\x32\x05.Item\"(\n\x11UpdateItemRequest\x12\x13\n\x04item\x18\x01 \x01(\x0b\x32\x05.Item\")\n\x12UpdateItemResponse\x12\x13\n\x04item\x18\x01 \x01(\x0b\x32\x05.Item\"\x1f\n\x11\x44\x65leteItemRequest\x12\n\n\x02id\x18\x01 \x01(\t\"\x14\n\x12\x44\x65leteItemResponse\"o\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\r\n\x05title\x18\x03 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x05\x12\n\n\x02pv\x18\x06 \x01(\x05\x12\x0e\n\x06status\x18\x07 \x01(\x08\x32\xeb\x01\n\x03\x41PI\x12/\n\x08ListItem\x12\x10.ListItemRequest\x1a\x11.ListItemResponse\x12!\n\x07GetItem\x12\x0f.GetItemRequest\x1a\x05.Item\x12\"\n\x07\x41\x64\x64Item\x12\x05.Item\x1a\x10.AddItemResponse\x12\x35\n\nUpdateItem\x12\x12.UpdateItemRequest\x1a\x13.UpdateItemResponse\x12\x35\n\nDeleteItem\x12\x12.DeleteItemRequest\x1a\x13.DeleteItemResponseb\x06proto3')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETITEMREQUEST = _descriptor.Descriptor(
  name='GetItemRequest',
  full_name='GetItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='GetItemRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=13,
  serialized_end=41,
)


_LISTITEMREQUEST = _descriptor.Descriptor(
  name='ListItemRequest',
  full_name='ListItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='page', full_name='ListItemRequest.page', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit', full_name='ListItemRequest.limit', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=43,
  serialized_end=89,
)


_LISTITEMRESPONSE = _descriptor.Descriptor(
  name='ListItemResponse',
  full_name='ListItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='ListItemResponse.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='total', full_name='ListItemResponse.total', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='prevPage', full_name='ListItemResponse.prevPage', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='nextPage', full_name='ListItemResponse.nextPage', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=91,
  serialized_end=182,
)


_ADDITEMRESPONSE = _descriptor.Descriptor(
  name='AddItemResponse',
  full_name='AddItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='AddItemResponse.item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=184,
  serialized_end=222,
)


_UPDATEITEMREQUEST = _descriptor.Descriptor(
  name='UpdateItemRequest',
  full_name='UpdateItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='UpdateItemRequest.item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=224,
  serialized_end=264,
)


_UPDATEITEMRESPONSE = _descriptor.Descriptor(
  name='UpdateItemResponse',
  full_name='UpdateItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='item', full_name='UpdateItemResponse.item', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=266,
  serialized_end=307,
)


_DELETEITEMREQUEST = _descriptor.Descriptor(
  name='DeleteItemRequest',
  full_name='DeleteItemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='DeleteItemRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=309,
  serialized_end=340,
)


_DELETEITEMRESPONSE = _descriptor.Descriptor(
  name='DeleteItemResponse',
  full_name='DeleteItemResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=342,
  serialized_end=362,
)


_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Item.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='Item.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='title', full_name='Item.title', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='Item.description', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='price', full_name='Item.price', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pv', full_name='Item.pv', index=5,
      number=6, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='status', full_name='Item.status', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=475,
)

_LISTITEMRESPONSE.fields_by_name['items'].message_type = _ITEM
_ADDITEMRESPONSE.fields_by_name['item'].message_type = _ITEM
_UPDATEITEMREQUEST.fields_by_name['item'].message_type = _ITEM
_UPDATEITEMRESPONSE.fields_by_name['item'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['GetItemRequest'] = _GETITEMREQUEST
DESCRIPTOR.message_types_by_name['ListItemRequest'] = _LISTITEMREQUEST
DESCRIPTOR.message_types_by_name['ListItemResponse'] = _LISTITEMRESPONSE
DESCRIPTOR.message_types_by_name['AddItemResponse'] = _ADDITEMRESPONSE
DESCRIPTOR.message_types_by_name['UpdateItemRequest'] = _UPDATEITEMREQUEST
DESCRIPTOR.message_types_by_name['UpdateItemResponse'] = _UPDATEITEMRESPONSE
DESCRIPTOR.message_types_by_name['DeleteItemRequest'] = _DELETEITEMREQUEST
DESCRIPTOR.message_types_by_name['DeleteItemResponse'] = _DELETEITEMRESPONSE
DESCRIPTOR.message_types_by_name['Item'] = _ITEM

GetItemRequest = _reflection.GeneratedProtocolMessageType('GetItemRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETITEMREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:GetItemRequest)
  ))
_sym_db.RegisterMessage(GetItemRequest)

ListItemRequest = _reflection.GeneratedProtocolMessageType('ListItemRequest', (_message.Message,), dict(
  DESCRIPTOR = _LISTITEMREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:ListItemRequest)
  ))
_sym_db.RegisterMessage(ListItemRequest)

ListItemResponse = _reflection.GeneratedProtocolMessageType('ListItemResponse', (_message.Message,), dict(
  DESCRIPTOR = _LISTITEMRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:ListItemResponse)
  ))
_sym_db.RegisterMessage(ListItemResponse)

AddItemResponse = _reflection.GeneratedProtocolMessageType('AddItemResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDITEMRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:AddItemResponse)
  ))
_sym_db.RegisterMessage(AddItemResponse)

UpdateItemRequest = _reflection.GeneratedProtocolMessageType('UpdateItemRequest', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEITEMREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:UpdateItemRequest)
  ))
_sym_db.RegisterMessage(UpdateItemRequest)

UpdateItemResponse = _reflection.GeneratedProtocolMessageType('UpdateItemResponse', (_message.Message,), dict(
  DESCRIPTOR = _UPDATEITEMRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:UpdateItemResponse)
  ))
_sym_db.RegisterMessage(UpdateItemResponse)

DeleteItemRequest = _reflection.GeneratedProtocolMessageType('DeleteItemRequest', (_message.Message,), dict(
  DESCRIPTOR = _DELETEITEMREQUEST,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:DeleteItemRequest)
  ))
_sym_db.RegisterMessage(DeleteItemRequest)

DeleteItemResponse = _reflection.GeneratedProtocolMessageType('DeleteItemResponse', (_message.Message,), dict(
  DESCRIPTOR = _DELETEITEMRESPONSE,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:DeleteItemResponse)
  ))
_sym_db.RegisterMessage(DeleteItemResponse)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
  DESCRIPTOR = _ITEM,
  __module__ = 'api_pb2'
  # @@protoc_insertion_point(class_scope:Item)
  ))
_sym_db.RegisterMessage(Item)


try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class APIStub(object):

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.ListItem = channel.unary_unary(
          '/API/ListItem',
          request_serializer=ListItemRequest.SerializeToString,
          response_deserializer=ListItemResponse.FromString,
          )
      self.GetItem = channel.unary_unary(
          '/API/GetItem',
          request_serializer=GetItemRequest.SerializeToString,
          response_deserializer=Item.FromString,
          )
      self.AddItem = channel.unary_unary(
          '/API/AddItem',
          request_serializer=Item.SerializeToString,
          response_deserializer=AddItemResponse.FromString,
          )
      self.UpdateItem = channel.unary_unary(
          '/API/UpdateItem',
          request_serializer=UpdateItemRequest.SerializeToString,
          response_deserializer=UpdateItemResponse.FromString,
          )
      self.DeleteItem = channel.unary_unary(
          '/API/DeleteItem',
          request_serializer=DeleteItemRequest.SerializeToString,
          response_deserializer=DeleteItemResponse.FromString,
          )


  class APIServicer(object):

    def ListItem(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def GetItem(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def AddItem(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def UpdateItem(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')

    def DeleteItem(self, request, context):
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_APIServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'ListItem': grpc.unary_unary_rpc_method_handler(
            servicer.ListItem,
            request_deserializer=ListItemRequest.FromString,
            response_serializer=ListItemResponse.SerializeToString,
        ),
        'GetItem': grpc.unary_unary_rpc_method_handler(
            servicer.GetItem,
            request_deserializer=GetItemRequest.FromString,
            response_serializer=Item.SerializeToString,
        ),
        'AddItem': grpc.unary_unary_rpc_method_handler(
            servicer.AddItem,
            request_deserializer=Item.FromString,
            response_serializer=AddItemResponse.SerializeToString,
        ),
        'UpdateItem': grpc.unary_unary_rpc_method_handler(
            servicer.UpdateItem,
            request_deserializer=UpdateItemRequest.FromString,
            response_serializer=UpdateItemResponse.SerializeToString,
        ),
        'DeleteItem': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteItem,
            request_deserializer=DeleteItemRequest.FromString,
            response_serializer=DeleteItemResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'API', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaAPIServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def ListItem(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def GetItem(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def AddItem(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def UpdateItem(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)
    def DeleteItem(self, request, context):
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaAPIStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    def ListItem(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    ListItem.future = None
    def GetItem(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    GetItem.future = None
    def AddItem(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    AddItem.future = None
    def UpdateItem(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    UpdateItem.future = None
    def DeleteItem(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      raise NotImplementedError()
    DeleteItem.future = None


  def beta_create_API_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('API', 'AddItem'): Item.FromString,
      ('API', 'DeleteItem'): DeleteItemRequest.FromString,
      ('API', 'GetItem'): GetItemRequest.FromString,
      ('API', 'ListItem'): ListItemRequest.FromString,
      ('API', 'UpdateItem'): UpdateItemRequest.FromString,
    }
    response_serializers = {
      ('API', 'AddItem'): AddItemResponse.SerializeToString,
      ('API', 'DeleteItem'): DeleteItemResponse.SerializeToString,
      ('API', 'GetItem'): Item.SerializeToString,
      ('API', 'ListItem'): ListItemResponse.SerializeToString,
      ('API', 'UpdateItem'): UpdateItemResponse.SerializeToString,
    }
    method_implementations = {
      ('API', 'AddItem'): face_utilities.unary_unary_inline(servicer.AddItem),
      ('API', 'DeleteItem'): face_utilities.unary_unary_inline(servicer.DeleteItem),
      ('API', 'GetItem'): face_utilities.unary_unary_inline(servicer.GetItem),
      ('API', 'ListItem'): face_utilities.unary_unary_inline(servicer.ListItem),
      ('API', 'UpdateItem'): face_utilities.unary_unary_inline(servicer.UpdateItem),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_API_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('API', 'AddItem'): Item.SerializeToString,
      ('API', 'DeleteItem'): DeleteItemRequest.SerializeToString,
      ('API', 'GetItem'): GetItemRequest.SerializeToString,
      ('API', 'ListItem'): ListItemRequest.SerializeToString,
      ('API', 'UpdateItem'): UpdateItemRequest.SerializeToString,
    }
    response_deserializers = {
      ('API', 'AddItem'): AddItemResponse.FromString,
      ('API', 'DeleteItem'): DeleteItemResponse.FromString,
      ('API', 'GetItem'): Item.FromString,
      ('API', 'ListItem'): ListItemResponse.FromString,
      ('API', 'UpdateItem'): UpdateItemResponse.FromString,
    }
    cardinalities = {
      'AddItem': cardinality.Cardinality.UNARY_UNARY,
      'DeleteItem': cardinality.Cardinality.UNARY_UNARY,
      'GetItem': cardinality.Cardinality.UNARY_UNARY,
      'ListItem': cardinality.Cardinality.UNARY_UNARY,
      'UpdateItem': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'API', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
