version: "2"
services:
  mysql:
    image: mysql:5.7
    restart: always
    env_file: .env
#    volumes:
#      - '/var/lib/mysql'
  app:
    build: .
    image: mikoim/mercari
    restart: always
    env_file: .env
    ports:
      - '3000:3000'
    depends_on:
      - mysql
