version: "2"
services:
  redis:
    image: redis
  mysql:
    image: mysql
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - redis
      - mysql
    networks:
      - default
    volumes:
      - .:/app
    command: []